---
- name: Write swapfile
  command: |
    fallocate -l {{ swapfile_size }} {{ swapfile_path }} creates={{ swapfile_path }}
  register: write_swapfile
  when: swapfile_size != false

- name: Set swapfile permissions
  file: path={{ swapfile_path }} mode=600
  when: swapfile_size != false

- name: Make swapfile
  ignore_errors: yes
  command: mkswap {{ swapfile_path }}
  when: swapfile_size != false

- name: Create systemd unit file
  template:
    src: swapfile.swap.j2
    dest: /etc/systemd/system/swapfile.swap
    owner: root
    group: root
    mode: 0644

- name: Enable systemctl
  command:
    systemctl enable --now swapfile.swap
  when: swapfile_size != false

- name: Configure vm.swappiness
  lineinfile: dest=/etc/sysctl.d/80-swappiness.conf line="vm.swappiness={{ swapfile_swappiness }}" regexp="^vm.swappiness[\s]?=" state=present create=yes mode=0644 owner=root group=root
  notify: Reload sysctl
  when: swapfile_swappiness != false
